Repository capitalone/federated-model-aggregation, pull requests merged in 2023-03, with the labels that each got.

#4 GH Actions Testing Workflow
  .github/workflows/test-python-package.yml
  aggregator/.pre-commit-config.yaml
  aggregator/Pipfile
  api_service/.pre-commit-config.yaml
  api_service/Pipfile
  clients/python_client/.pre-commit-config.yaml
  clients/python_client/Pipfile
  connectors/django/.pre-commit-config.yaml
  connectors/django/Pipfile
  connectors/django/fma_django_api/v1/views.py
  examples/.pre-commit-config.yaml
  examples/django-deployment/Pipfile
  fma-core/.pre-commit-config.yaml
  fma-core/Pipfile
  fma-core/fma_core/conf.py
Labels: enhancement

#15 Deployment bug fixes fork
  aggregator/Makefile
  aggregator/Pipfile
  aggregator/README.md
  aggregator/federated_learning_project/fma_settings.py
  aggregator/setup.cfg
  api_service/Makefile
  api_service/Pipfile
  api_service/README.md
  api_service/federated_learning_project/fma_settings.py
  api_service/federated_learning_project/settings_local.py
  api_service/federated_learning_project/settings_remote.py
  api_service/setup.cfg
  connectors/django/fma_django_connectors/tests/fma_settings.py
  examples/django-deployment/README.md
  examples/django-deployment/federated_learning_project/fma_settings.py
  fma-core/fma_core/__init__.py
  fma-core/fma_core/tests/test_base.py
  fma-core/fma_core/workflows/api_handler_factory.py
  fma-core/fma_core/workflows/tasks.py
  terraform_deploy/deploy_vars.tf
Labels: bug, enhancement

#16 Quick Typo Fix
  clients/python_client/setup.py
Labels: bug
